---
- dest: ./src/components/
  friendlyName: FunctionComponent(FC)
  nameCase: pascal
  structure:
    - type: file
      name: index
      extension: ts
      content:
        src: ./_tpl/FC/Component.index.ts
    - type: file
      suffix: .styles
      extension: ts
      content:
        src: ./_tpl/FC/Component.styles.ts
    - type: file
      suffix: .types
      extension: ts
      content:
        src: ./_tpl/FC/Component.types.ts
    - type: file
      extension: tsx
      content:
        src: ./_tpl/FC/Component.base.tsx
    - type: folder
      name: tests
      content:
        - type: file
          suffix: .test
          extension: tsx
          content:
            src: ./_tpl/Component.tst.tsx
    - type: folder
      name: stories
      content:
        - type: file
          suffix: .stories
          extension: tsx
          content:
            src: ./_tpl/Component.stories.tsx
